# -*- coding: utf-8 -*-
"""translation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13tGgLIX_TANL8V-ZTxW1SsHcV4n35uWX
"""

from googletrans import Translator

translator = Translator()

sentence = 'Hi'  # 언어 감지를 원하는 문장 설정

detected = translator.detect(sentence)   # 입력한 문장의 언어 감지
print(detected)
print(detected.lang)

result = translator.translate(sentence, 'ko')

print(result)

